name: postman-api-tests
on: push

jobs:
  test-client-address-api:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
           - 27017:27017
      client-address-app:
        image: scottiecrump/client-address-next:latest
        ports:
           - 3000:3000
        env:
          MONGO_URI: "mongodb://mongo:27017/addressbook"
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install newman dependencies
      run: npm install -g newman newman-reporter-htmlextra
    - run: npm test
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: newman-report
        path: newman
        retention-days: 5


